Topic relay
libp2p/go-libp2p-pubsub pull request #317
Opened 2020-04-30 13:05 UTC by lukasz-zimnoch

Refs #28 #292 

This pull request ships an implementation of the topic `Relay` operation. That opens the possibility to take part in voluntary topic dissemination by all interested nodes without the need for subscribing.  

**Implementation details**

This implementation tries to follow @vyzo [comment](https://github.com/libp2p/go-libp2p-pubsub/issues/292#issuecomment-619058811) thus it uses a relay reference counter and try to not conflate with subscriptions. However, regarding peer discovery, we probably must follow the same logic as subscriptions which is reflected in the implementation. Also, relays canceling logic has probably a place for improvements so I'd appreciate suggestions on how I can do it better to satisfy all possible use cases.

2020-04-30 16:07 UTC, vyzo requested changes
Thank you! This overall looks good, just a few minor issues that should be addressed.

2020-04-30 16:07 UTC, vyzo commented on pubsub.go
> +	if p.myRelays[topic] == 0 && len(p.mySubs[topic]) == 0 {
It is probably cleaner to merge the second conditional with the body of the first:
```
If p.myRelays[topic] == 0 {
  delete(p.myRelays, topic)

  if len(p.mySubs[topic]) == 0 {
   ...
  }
}
```

2020-04-30 16:07 UTC, vyzo commented on pubsub.go
> +		}
It is possible to invoke the cancellation function more than once, and cancel unrelated relaying operations.
I think it is best to keep a variable in the closure (a boolean would do) that gets poisoned if it is invoked once, and avoids the notification in subsequent calls.

2020-04-30 16:07 UTC, vyzo commented on pubsub.go
> +		}
We would also want a test for this behaviour.

2020-04-30 16:07 UTC, vyzo commented on topic_test.go
> +	}
This results in a race in the test (see the travis failure),
If you need to examine the internal state of pubsub, you can use the eval channel:
```
pubsubs[0].eval <- func() {
  ...
}
```

2020-04-30 16:07 UTC, vyzo commented on topic_test.go
> +	}
same here.

2020-04-30 16:07 UTC, vyzo commented on pubsub.go
> +	p.myRelays[topic]++
We need to increment the counter _before_ trying to announce; the check should then be for the counter would be against 1.

2020-04-30 16:07 UTC, vyzo commented on pubsub.go
> +	p.myRelays[topic]++
Note that it is not necessary a problem for the code as it is written right now, but it's subtlety we would like to avoid.

2020-04-30 16:09 UTC, vyzo commented
Do you mind rebasing on master? The branch is currently out of date, which would prevent us from merging.

2020-05-01 09:01 UTC, lukasz-zimnoch commented
Thanks for review @vyzo! All comments addressed.

2020-05-01 09:20 UTC, vyzo approved these changes
thank you!

2020-05-01 09:22 UTC, merged