Refactor Gossipsub Parameters To Make Them More Configurable
libp2p/go-libp2p-pubsub pull request #365
Opened 2020-07-27 15:53 UTC by nisdas

Resolves #364 

- [x] Add a special gossipsub parameter config to be able to instantiate the router with.
- [x] Add a pubsub option that allows a custom config to be set when creating the pubsub object.
- [x] Fix references so that only the param object in the gossipsub router struct is accessed instead of the
default global parameter.
- [x] Add a unit test to ensure this feature works as expected.

cc @vyzo @raulk

2020-07-27 16:26 UTC, vyzo requested changes
Thank you!

A couple of notes on how to make things better:
1) Naming: drop the GossipSub prefix in the params struct, it's redundant
2) Grouping: let's use the params struct directly instead of copying values right and left, it's confusing
3) Indirection: let's keep the params struct as a struct (not a pointer) to avoid the extra memory indirection.

2020-07-27 16:26 UTC, vyzo commented on gossipsub.go
> +	GossipSubD int
let's drop the GossipSub prefix in these variables, it's redundant.

2020-07-27 16:26 UTC, vyzo commented on gossipsub.go
> +		paramsCfg: params,
let's just call this params.

2020-07-27 16:26 UTC, vyzo commented on gossipsub.go
> +		Dlazy:  params.GossipSubDlazy,
let's just use the params struct directly, this is getting messy.

2020-07-27 16:26 UTC, vyzo commented on gossipsub.go
> +		Dlazy:  params.GossipSubDlazy,
Also, let's make the params object a plain struct, not a pointer so that there is no extra indirection.

2020-08-14 17:18 UTC, jacobheun commented
@nisdas can you take a look at @vyzo's feedback so we can move this forward?

2020-08-17 16:41 UTC, nisdas commented
Hey @jacobheun , yeap I will try to get on this as soon as possible. I am a bit swamped right now but I will address the feedback as soon as I can.

2020-08-26 12:13 UTC, nisdas commented
@vyzo @jacobheun 
Sorry for the delay, but this is ready for another look

2020-10-21 23:32 UTC, protolambda commented
I am interested in this configuration feature as well. Can we move this forward? Do you need any help?

2020-11-17 22:40 UTC, protolambda commented
Is anyone looking at merging this feature? Can I help?

2020-11-18 01:28 UTC, nisdas commented
@protolambda I will resync with master and fix conflicts by today

2021-03-29 15:18 UTC, BigLep commented
@nisdas: what's the status here?  Will you be able to fix the tests?

2021-03-30 10:39 UTC, nisdas commented
@BigLep I didn't get another review for this, so I havent been keeping it updated. However all tests should pass, the previous failure seemed unrelated to the PR(1 test run passed and the other exited abruptly with no test error).

2021-04-05 15:16 UTC, aschmahmann commented
Do you mind rebasing on master? CI should be passing now.

2021-04-06 06:41 UTC, nisdas commented
Alright done @aschmahmann , I have resolved the previous conflicts

2021-04-12 15:09 UTC, BigLep commented
@Stebalien is working on getting CI updates to run.

2021-04-12 15:13 UTC, Stebalien commented
This didn't need a rebase. Trying to kick CI... and failing, apparently.

2021-04-12 15:21 UTC, Stebalien commented
Let's wait for #415. That should fix CI.

2021-05-03 15:53 UTC, Stebalien commented
I'm going to re-open this as a new PR to get CI to run.

2021-05-03 15:53 UTC, closed without merging

2021-05-03 15:59 UTC, Stebalien commented
Merged. Thanks all for your patience.