add support for custom protocol matching function
libp2p/go-libp2p-pubsub pull request #440
Opened 2021-07-29 19:01 UTC by richard-ramos

This allows setting a custom protocol matching function.
```
fullTextMatch := func(expectedProtocol string) func(string) bool {
    return func(protocolToVerify string) bool {
	return protocolToVerify == expectedProtocol
    }
}

// create a new PubSub service using the GossipSub router
ps, err := pubsub.NewGossipSub(ctx, h, pubsub.WithProtocolMatchFunction(fullTextMatch))
```

Could potentially be used to allow semver matching
```go
protoMinor := protocol.ID("/testing/1.2.0")
mfunc, err := helpers.MultistreamSemverMatcher(protoMinor)
if err != nil {
    t.Fatal(err)
}
ps, err := pubsub.NewGossipSub(ctx, h, 
     pubsub.WithProtocolMatchFunction(mfunc),
     pubsub.WithGossipSubProtocols([]protocol.ID{pubsub.GossipSubID_v11, pubsub.GossipSubID_v10, pubsub.FloodSubID, protoMinor}, pubsub.GossipSubDefaultFeatures)
)

```

2021-07-29 19:09 UTC, vyzo requested changes
Thank you, this looks useful.

A couple of small changes are needed:
- It should probably be combined with the appropriate feature test function in gossipsub.
  Mind adding some about this in the documentation?
- No need to use a pointer! functions can be tested against nil with `!=`

2021-07-29 19:09 UTC, vyzo commented on pubsub.go
> +type MatchingFunction func(string) func(string) bool
Can you make this an alias and call it `ProtocolMatchFn`?

So
```
type ProtocolMatchFn = ...
```

2021-07-29 19:09 UTC, vyzo commented on pubsub.go
> +	protoMatchFunc *MatchingFunction
no need for a pointer here, you can test a function against nil.

2021-07-29 19:09 UTC, vyzo commented on pubsub.go
> +			h.SetStreamHandlerMatch(id, (*ps.protoMatchFunc)(string(id)), ps.handleNewStream)
no need for the indirection if you don't use a pointer.

2021-07-29 19:09 UTC, vyzo commented on pubsub.go
> +		ps.protoMatchFunc = &m
and here, no need to take a pointer.

2021-07-29 19:10 UTC, vyzo commented
Also, can you add a test?

2021-07-30 05:34 UTC, vyzo reviewed
thank you, this is looking good. Just a couple of minor things to fix and we can merge.

2021-07-30 05:34 UTC, vyzo commented on pubsub.go
> +		protoMatchFunc:        nil,
we don't need to initialize this, the default is fine.

2021-07-30 05:34 UTC, vyzo commented on pubsub.go
> +// WithGossipSubProtocols feature function for checking if a protocol is supported
I would say here "Should be combined ... for checking if certain protocol features are supported"

2021-07-30 05:34 UTC, vyzo commented on pubsub.go
> +		protoMatchFunc:        nil,
Note that we do it for `signKey` to be explicit about it, as these are grouped together.

2021-07-30 12:59 UTC, richard-ramos commented
I finished the required changes. Thank you for the code review!

2021-07-30 13:57 UTC, vyzo approved these changes

2021-07-30 13:57 UTC, merged

2021-07-30 13:57 UTC, vyzo commented
thank you!